import type { Chapter, Paper } from "@/lib/types";

export const AQA_ECON_PAPERS: Paper[] = [
  {
    id: "econ-p1",
    subject: "aqa-economics",
    code: "7136/1",
    title: "Paper 1: Markets and the operation of the real economy",
    durationMinutes: 120,
    marks: 80,
    weighting: 35,
  },
  {
    id: "econ-p2",
    subject: "aqa-economics",
    code: "7136/2",
    title: "Paper 2: National economy and the global economy",
    durationMinutes: 120,
    marks: 80,
    weighting: 35,
  },
  {
    id: "econ-p3",
    subject: "aqa-economics",
    code: "7136/3",
    title: "Paper 3: 20-mark synoptic essay",
    durationMinutes: 120,
    marks: 20,
    weighting: 30,
  },
];

const MICRO = "Microeconomics";
const MACRO = "Macroeconomics";
const FIN = "Financial markets";
const INTL = "International economy";
const BOARD = "AQA AS and A-level Economics (7135/7136)";

export const AQA_ECON_MICRO: Chapter[] = [
  {
    id: "econ-4.1.1",
    subject: "aqa-economics",
    specRef: "4.1.1",
    title: "Economic methodology and the economic problem",
    group: MICRO,
    content: [
      "Economics as a social science; the difference between positive and normative statements",
      "Value judgements and how they influence economic decision making and policy",
      "The central purpose of economic activity and the nature and purpose of economic activity",
      "Economic resources: land, labour, capital and enterprise",
      "Scarcity, choice and the allocation of resources; the environment as a scarce economic resource",
      "Opportunity cost; the concept and calculation of opportunity cost",
      "Production possibility diagrams and the use of these diagrams to illustrate features of the economy",
    ],
    skills: ["methodology", "opportunity-cost", "diagrams"],
    prerequisites: [],
    weight: 1.1,
    paper: "econ-p1",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.2",
    subject: "aqa-economics",
    specRef: "4.1.2",
    title: "Individual economic decision making",
    group: MICRO,
    content: [
      "Consumer behaviour and utility theory: total utility, marginal utility and diminishing marginal utility",
      "Non-price determinants of demand: income, tastes, expectations, substitutes, complements",
      "Imperfect information and its importance for decision making",
      "Aspects of behavioural economic theory: bounded rationality, bounded self-control, heuristics, framing, anchoring, social norms and rules of thumb",
      "Behavioural economics and economic policy: choice architecture, restricted and mandated choice, nudge theory",
      "The effect of asymmetric information on markets and on economic agents",
    ],
    skills: ["behavioural-economics", "consumer-behaviour", "evaluation"],
    prerequisites: ["econ-4.1.1"],
    weight: 1.2,
    paper: "econ-p1",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.3",
    subject: "aqa-economics",
    specRef: "4.1.3",
    title: "Determinants of the demand for goods and services",
    group: MICRO,
    content: [
      "The law of demand and the determinants of demand for goods and services",
      "Substitutes and complements, and the effect of a change in their price",
      "Price elasticity of demand: calculation and interpretation, including own-price cross-price",
      "Income elasticity of demand and the classification of income elastic and inelastic goods",
      "Calculating and interpreting PED, XED and YED from data",
    ],
    skills: ["elasticity", "numerical", "diagrams"],
    prerequisites: ["econ-4.1.2"],
    weight: 1.4,
    paper: "econ-p1",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.4",
    subject: "aqa-economics",
    specRef: "4.1.4",
    title: "Production, costs and revenue",
    group: MICRO,
    content: [
      "Production and productivity; the law of diminishing returns and returns to scale",
      "Specialisation, division of labour and exchange; the advantages and disadvantages of specialisation",
      "Costs of production: fixed, variable, total, average and marginal costs",
      "Short-run and long-run costs; economies and diseconomies of scale",
      "Revenue: total, average and marginal revenue; profit-maximising output where MC = MR",
      "Technological change and its effect on costs, revenue and market structure",
    ],
    skills: ["costs", "numerical", "diagrams"],
    prerequisites: ["econ-4.1.3"],
    weight: 1.4,
    paper: "econ-p1",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.5",
    subject: "aqa-economics",
    specRef: "4.1.5",
    title: "Perfect competition, imperfect competition and monopoly",
    group: MICRO,
    content: [
      "Market structures: market size, market share, concentration ratio and the four market structures",
      "Objectives of firms: profit maximisation, sales maximisation, satisficing, social and ethical objectives",
      "Perfect competition: assumptions, price taker behaviour, short-run and long-run equilibrium",
      "Monopoly: barriers to entry, natural monopoly, price discrimination",
      "Price discrimination: first, second and third degree and the conditions for each",
      "Monopoly profit maximising output and price where MC = MR; allocative and productive efficiency",
      "The role and impact of competition policy, the CMA and competition law",
    ],
    skills: ["market-structures", "numerical", "diagrams", "evaluation"],
    prerequisites: ["econ-4.1.4"],
    weight: 1.5,
    paper: "econ-p1",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.6",
    subject: "aqa-economics",
    specRef: "4.1.6",
    title: "The operation of markets and market failure",
    group: MICRO,
    content: [
      "Allocative, dynamic and productive efficiency; why markets may fail to produce efficient outcomes",
      "Externalities: negative and positive, and the effect on the social optimum",
      "Common pool resource problems: public goods, merit goods and demerit goods",
      "Market failure caused by uncertainty, asymmetric information, principal-agent and moral hazard problems",
      "Government intervention: indirect and direct taxes, subsidies, regulation and tradable permits",
      "Second best theory and the limitations of government intervention",
    ],
    skills: ["market-failure", "diagrams", "evaluation"],
    prerequisites: ["econ-4.1.5"],
    weight: 1.5,
    paper: "econ-p1",
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.7",
    subject: "aqa-economics",
    specRef: "4.1.7",
    title: "The national economy in a global context",
    group: MICRO,
    content: [
      "The role of the government in the economy; the aims of economic policy",
      "Economic growth: the meaning of economic growth and its measurement",
      "Economic development and the distinction between growth and development",
      "Economic growth in the UK: sources of growth and the determinants of investment",
      "The national income and product; GDP, GNP, per capita income and HDI",
    ],
    skills: ["growth", "diagrams", "evaluation"],
    prerequisites: ["econ-4.1.6"],
    weight: 1,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.8",
    subject: "aqa-economics",
    specRef: "4.1.8",
    title: "The labour market",
    group: MICRO,
    content: [
      "The demand for labour and marginal productivity theory",
      "Influences upon the supply of labour to different markets, including migration",
      "The determination of relative wage rates and levels of employment in perfectly and imperfectly competitive labour markets",
      "The influence of trade unions in determining wages and levels of employment; the national minimum wage",
      "Discrimination in the labour market: occupational, spatial and gender discrimination",
      "Job search and the use of unemployment data; the interpretation of wage and employment data",
    ],
    skills: ["labour-market", "numerical", "evaluation"],
    prerequisites: ["econ-4.1.6"],
    weight: 1.4,
    paper: "econ-p1",
    examBoard: BOARD,
  },
  {
    id: "econ-4.1.9",
    subject: "aqa-economics",
    specRef: "4.1.9",
    title: "Poverty and inequality",
    group: MICRO,
    content: [
      "Inequality: income inequality and wealth inequality, and the measurement of each",
      "The Gini coefficient and how it is calculated and interpreted",
      "The extent and causes of poverty, including the distinction between absolute and relative poverty",
      "Inequality of opportunity and intergenerational mobility",
      "Government policy to reduce inequality: progressive taxation, negative income tax and benefit reform",
    ],
    skills: ["inequality", "numerical", "evaluation"],
    prerequisites: ["econ-4.1.8"],
    weight: 1.3,
    paper: "econ-p1",
    examBoard: BOARD,
  },
];

export const AQA_ECON_MACRO: Chapter[] = [
  {
    id: "econ-4.2.1",
    subject: "aqa-economics",
    specRef: "4.2.1",
    title: "Macroeconomic objectives and theory",
    group: MACRO,
    content: [
      "Macroeconomic objectives: growth, unemployment, inflation and the trade-off between them",
      "The circular flow of income: the flow of income between households, firms, government and overseas",
      "Leakages and injections in the circular flow of income",
      "The basic economic problem at national level; how national economic objectives may conflict",
      "The government as an agent of economic policy",
    ],
    skills: ["circular-flow", "diagrams", "methodology"],
    prerequisites: ["econ-4.1.7"],
    weight: 1.2,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.2.2",
    subject: "aqa-economics",
    specRef: "4.2.2",
    title: "Economic growth and the economic cycle",
    group: MACRO,
    content: [
      "The meaning of economic growth and its measurement using real and nominal measures",
      "Growth and the business cycle: expansion, peak, contraction and trough",
      "Growth and the productive potential of an economy; growth in the short run and long run",
      "Long-run growth versus short-run growth and the use of diagrams to show a growth curve",
    ],
    skills: ["growth", "diagrams"],
    prerequisites: ["econ-4.2.1"],
    weight: 1.1,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.2.3",
    subject: "aqa-economics",
    specRef: "4.2.3",
    title: "Aggregate demand and the level of economic activity",
    group: MACRO,
    content: [
      "The components of aggregate demand: C, I, G and (X \u2212 M)",
      "Aggregate supply: short-run and long-run aggregate supply curves",
      "Equilibrium output and the determination of the price level in the AD/AS model",
      "The multiplier effect and the marginal propensity to consume; the calculation of the multiplier",
      "Shifts in aggregate demand and their effect on output and the price level",
      "UK multipliers and the effect of an increase or decrease in injections",
    ],
    skills: ["ad-as", "multiplier", "numerical", "diagrams"],
    prerequisites: ["econ-4.2.2"],
    weight: 1.5,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.2.4",
    subject: "aqa-economics",
    specRef: "4.2.4",
    title: "Economic performance",
    group: MACRO,
    content: [
      "Unemployment: definition and calculation, cyclical, structural, frictional, seasonal and classical",
      "Deflation and inflation: definition, calculation using the CPI, and measurement using index numbers",
      "Incentives to reduce unemployment and the impact of policy on the labour market",
      "Labour market flexibility and the trade-off between unemployment and inflation (Phillips curve)",
      "Causes of inflation and the effects of inflation on stakeholders, including savers and borrowers",
      "Incentives to reduce inflation and the effect of inflation on the economy",
    ],
    skills: ["inflation", "unemployment", "numerical", "diagrams"],
    prerequisites: ["econ-4.2.3"],
    weight: 1.5,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.2.5",
    subject: "aqa-economics",
    specRef: "4.2.5",
    title: "Macroeconomic policy",
    group: MACRO,
    content: [
      "The objectives and limits of monetary policy and the transmission mechanism",
      "Expansionary and contractionary fiscal policy and the effect on AD, output, unemployment and inflation",
      "Automatic stabilisers and discretionary fiscal policy",
      "Supply-side policies: market-based and interventionist, and their effect on LRAS",
      "The effectiveness of fiscal policy, including time lags, crowding out and the public sector borrowing requirement",
      "Political constraints on economic policy and the problems of election cycles",
    ],
    skills: ["fiscal-policy", "monetary-policy", "diagrams", "evaluation"],
    prerequisites: ["econ-4.2.4"],
    weight: 1.5,
    paper: "econ-p2",
    examBoard: BOARD,
  },
];

export const AQA_ECON_FINANCIAL: Chapter[] = [
  {
    id: "econ-4.3.1",
    subject: "aqa-economics",
    specRef: "4.3.1",
    title: "Financial markets and financial instruments",
    group: FIN,
    content: [
      "Stock markets and the functions of stock exchanges; primary and secondary markets",
      "Money markets: functions and instruments, including commercial paper, Treasury bills and certificates of deposit",
      "Bond markets: features of bonds, including nominal value, coupon rate, maturity and yield",
      "Foreign exchange markets and the determination of exchange rates",
      "Regulation of financial markets and the role of the FCA and the Bank of England",
    ],
    skills: ["financial-markets", "numerical", "evaluation"],
    prerequisites: ["econ-4.2.5"],
    weight: 1.2,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.3.2",
    subject: "aqa-economics",
    specRef: "4.3.2",
    title: "Central banking and monetary policy",
    group: FIN,
    content: [
      "The functions of central banks and the objectives of monetary policy",
      "Expansionary and contractionary monetary policy and the effect on AD and the economy",
      "The transmission mechanism: from interest rate change to final demand",
      "Quantitative easing and its use in the UK following the financial crisis of 2008",
      "The limitations and lags of monetary policy, and the relationship with the Bank Rate and MPC",
    ],
    skills: ["monetary-policy", "diagrams", "evaluation"],
    prerequisites: ["econ-4.3.1"],
    weight: 1.3,
    paper: "econ-p2",
    examBoard: BOARD,
  },
];

export const AQA_ECON_INTERNATIONAL: Chapter[] = [
  {
    id: "econ-4.4.1",
    subject: "aqa-economics",
    specRef: "4.4.1",
    title: "International trade and global economic integration",
    group: INTL,
    content: [
      "The comparative advantage of trade and the gains from trade",
      "Absolute and comparative advantage; calculation of opportunity cost",
      "Free trade versus protectionism; tariffs, quotas and subsidy-based protectionism",
      "Trading blocs, the World Trade Organization and the reduction of trade barriers",
      "Globalisation: the causes and consequences of increased integration of the world economy",
    ],
    skills: ["trade", "numerical", "evaluation"],
    prerequisites: ["econ-4.3.2"],
    weight: 1.3,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.4.2",
    subject: "aqa-economics",
    specRef: "4.4.2",
    title: "International finance",
    group: INTL,
    content: [
      "The balance of payments: current account, capital account and financial account components",
      "Reasons for deficits and surpluses in the current and financial accounts",
      "Exchange rate systems: floating and fixed exchange rates",
      "Factors affecting exchange rates: interest rates, inflation, terms of trade and global sentiment",
      "The Marshall-Lerner condition and the effect of a depreciation on the current account",
      "Global financial institutions and the risk of financial instability",
    ],
    skills: ["bop", "exchange-rates", "numerical", "diagrams"],
    prerequisites: ["econ-4.4.1"],
    weight: 1.3,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.4.3",
    subject: "aqa-economics",
    specRef: "4.4.3",
    title: "Globalisation and emerging and developed economies",
    group: INTL,
    content: [
      "The global distribution of economic activity; patterns of growth in emerging and developed economies",
      "Globalisation of production: multinational corporations, global value chains and foreign direct investment",
      "Multinationals: advantages and disadvantages for a host economy and for a multinational",
      "The effect of trade on the distribution of income within and between countries",
    ],
    skills: ["globalisation", "evaluation"],
    prerequisites: ["econ-4.4.2"],
    weight: 1.1,
    paper: "econ-p2",
    examBoard: BOARD,
  },
  {
    id: "econ-4.4.4",
    subject: "aqa-economics",
    specRef: "4.4.4",
    title: "International development",
    group: INTL,
    content: [
      "Development indicators: GDP per head, GNI, HDI, MPI and the extent to which they are reliable",
      "Development, sustainability and the extent to which different countries are developing",
      "Aid: bilateral, multilateral, tied and untied aid, and the effectiveness of aid",
      "Development tradeoffs: environment, debt relief, market-oriented vs interventionist approaches",
      "The role of MNCs, debt relief, poverty reduction programmes and aid in development",
    ],
    skills: ["development", "evaluation"],
    prerequisites: ["econ-4.4.3"],
    weight: 1.2,
    paper: "econ-p2",
    examBoard: BOARD,
  },
];

export const AQA_ECON_CHAPTERS: Chapter[] = [
  ...AQA_ECON_MICRO,
  ...AQA_ECON_MACRO,
  ...AQA_ECON_FINANCIAL,
  ...AQA_ECON_INTERNATIONAL,
];
