import type { Chapter, Paper } from "@/lib/types";

export const EDXCEL_PAPERS: Paper[] = [
  {
    id: "em-p1",
    subject: "edexcel-mathematics",
    code: "9MA0/01",
    title: "Paper 1: Pure Mathematics 1",
    durationMinutes: 120,
    marks: 100,
    weighting: 33.33,
  },
  {
    id: "em-p2",
    subject: "edexcel-mathematics",
    code: "9MA0/02",
    title: "Paper 2: Pure Mathematics 2",
    durationMinutes: 120,
    marks: 100,
    weighting: 33.33,
  },
  {
    id: "em-p3",
    subject: "edexcel-mathematics",
    code: "9MA0/03",
    title: "Paper 3: Statistics and Mechanics",
    durationMinutes: 120,
    marks: 100,
    weighting: 33.34,
  },
];

const PURE = "Pure Mathematics";
const STATS = "Statistics";
const MECH = "Mechanics";

export const EDEXCEL_MATH_CHAPTERS: Chapter[] = [
  // ---------------------------------------------------------------- PURE 1
  {
    id: "em-1",
    subject: "edexcel-mathematics",
    specRef: "Topic 1",
    title: "Proof",
    group: PURE,
    content: [
      "Proof by mathematical induction, including the structure of base case, inductive hypothesis and inductive step",
      "Proof by contradiction, including the irrationality of 2 and the infinity of primes",
      "Proof by exhaustion",
      "Understand and use the notation n \u2208 \u212d and construct counter-examples",
      "Comprehend and critique mathematical arguments, proofs and justifications of methods and formulae",
    ],
    skills: ["proof", "algebra"],
    prerequisites: [],
    weight: 1,
    paper: "em-p1",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-2",
    subject: "edexcel-mathematics",
    specRef: "Topic 2",
    title: "Algebra and functions",
    group: PURE,
    content: [
      "Laws of indices for all rational exponents: a^m \u00d7 a^n = a^(m+n), a^m \u00f7 a^n = a^(m\u2212n), (a^m)^n = a^(mn)",
      "Surds and rationalising the denominator",
      "Expansion of quadratics, including completing the square and the discriminant",
      "Quadratic inequalities and the solution of simultaneous equations, including those with an unknown appearing in a denominator",
      "Quadratic simultaneous equations and the algebraic solution of cubic equations and inequalities",
      "Understand and use functions: domain, range, composite and inverse functions, including for modular, exponential, trigonometric and rational functions",
      "Understand the exponential function y = a^x in real, logarithmic, graphical and numerical forms, and the natural exponential function y = e^x",
      "Interpret the solution of f(x) = a in the context of a real-world problem",
      "Understand and use the modulus, absolute value and piecewise functions; sketch the graph of y = |f(x)| using supplied information",
    ],
    skills: ["algebra", "functions", "indices"],
    prerequisites: ["em-1"],
    weight: 1.3,
    paper: "em-p1",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-3",
    subject: "edexcel-mathematics",
    specRef: "Topic 3",
    title: "Coordinate geometry in the (x, y) plane",
    group: PURE,
    content: [
      "Equation of a straight line in the forms y \u2212 y\u2081 = m(x \u2212 x\u2081) and ax + by + c = 0",
      "The 2D Cartesian coordinate system, including the use of distance and midpoint formulae",
      "The 3D Cartesian coordinate system, including the coordinate axes and 3D vectors",
      "The equation of a circle, including the form (x \u2212 a)\u00b2 + (y \u2212 b)\u00b2 = r\u00b2, and the perpendicular bisector and perpendicular bisector of two line segments",
    ],
    skills: ["geometry", "algebra", "coordinate-geometry"],
    prerequisites: ["em-2"],
    weight: 1,
    paper: "em-p1",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-4",
    subject: "edexcel-mathematics",
    specRef: "Topic 4",
    title: "Sequences and series",
    group: PURE,
    content: [
      "Sigma notation, and use of summation, indexing and triangular numbers",
      "Arithmetic sequences and series, including the formula for the nth term and for the sum to n terms",
      "Arithmetic sequences and series, including the formula for the sum to n terms; summing a series to infinity where the ratio is between \u22121 and 1",
      "Geometric sequences and series, including the ratio test for convergence",
      "Binomial expansion and binomial coefficients for positive integer index n",
      "The binomial theorem, including expansion for rational index",
    ],
    skills: ["algebra", "sequences", "series"],
    prerequisites: ["em-2"],
    weight: 1.1,
    paper: "em-p1",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-5",
    subject: "edexcel-mathematics",
    specRef: "Topic 5",
    title: "Trigonometry",
    group: PURE,
    content: [
      "Radians, including arc length and the definition of radian measure",
      "Unit circle, including the exact values of sin, cos and tan in terms of \u03c0",
      "Sine, cosine and tangent rules, including the ambiguous case and area of a triangle",
      "Trigonometric identities and equations, including compound and double-angle formulae and solutions in a stated range",
      "Solution of trigonometric equations in radians and degrees in a given range, using a scientific calculator",
    ],
    skills: ["trigonometry", "geometry"],
    prerequisites: ["em-3"],
    weight: 1.3,
    paper: "em-p1",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-6",
    subject: "edexcel-mathematics",
    specRef: "Topic 6",
    title: "Exponentials and logarithms",
    group: PURE,
    content: [
      "Exponentials and logarithms: definition of log_a x, change of base, and laws of logarithms",
      "Solve equations of the form a^x = b, and logarithmic equations including those requiring a change of base",
      "Solve simultaneous equations involving exponentials and logarithms where algebra is used to reduce to a single equation",
    ],
    skills: ["algebra", "exponentials"],
    prerequisites: ["em-2"],
    weight: 1.1,
    paper: "em-p1",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-7",
    subject: "edexcel-mathematics",
    specRef: "Topic 7",
    title: "Differentiation",
    group: PURE,
    content: [
      "Differentiation of x^n for all real n, of exp x, of ln x, and of sin x, cos x, tan x",
      "Differentiation of sums and differences of polynomials",
      "First and second derivatives; interpret the derivative of a function as a rate of change",
      "Product, quotient and chain rule; differentiate implicitly, including the technique for logarithmic differentiation and differentiation of parametric equations",
      "Implicit and parametric differentiation, including the derivative of x^y",
    ],
    skills: ["calculus", "algebra"],
    prerequisites: ["em-2"],
    weight: 1.4,
    paper: "em-p2",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-8",
    subject: "edexcel-mathematics",
    specRef: "Topic 8",
    title: "Integration",
    group: PURE,
    content: [
      "Integration of x^n for all real n, of exp x, of 1/x, of sin x and cos x",
      "The meaning of the indefinite integral, and the family of antiderivatives; definite integrals as the limit of a sum and as an area under a curve",
      "The trapezium rule, including the formula and error bounds for a curve with given data points",
      "Integration by substitution and by parts, including integration of trigonometric and rational functions",
      "Integration of \u222b f(x) dx using a change of variable, and standard forms",
      "Volumes of revolution, including the disc, shell and washer methods; area between two curves",
    ],
    skills: ["calculus", "algebra"],
    prerequisites: ["em-7"],
    weight: 1.4,
    paper: "em-p2",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-9",
    subject: "edexcel-mathematics",
    specRef: "Topic 9",
    title: "Numerical methods",
    group: PURE,
    content: [
      "Location of roots of f(x) = 0 by change of sign, bisection and the Newton\u2013Raphson method",
      "Newton\u2013Raphson iterative formula, the conditions for convergence, and reasons a method may fail",
      "Fixed point iteration, including the form x_(n+1) = g(x_n), and the conditions for convergence",
      "Reduction to linear form to find a model, and interpreting the gradient in context",
    ],
    skills: ["numerical-methods", "algebra"],
    prerequisites: ["em-7"],
    weight: 0.9,
    paper: "em-p2",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-10",
    subject: "edexcel-mathematics",
    specRef: "Topic 10",
    title: "Vectors",
    group: PURE,
    content: [
      "Vectors in two and three dimensions; magnitude of a vector, sum and difference of vectors, scalar and vector multiples of a vector",
      "Position vectors of points relative to an origin; geometric interpretation of vector addition",
      "The magnitude of a position vector and the distance between two points in 2D and 3D",
      "Ratio theorem, section formula, and the use of position vectors to find the midpoint of a line segment AB",
      "Vector equation of a straight line, parametric form, and solving simultaneous vector equations",
      "Scalar product and its use to find the angle between two vectors; find the area of a parallelogram",
      "Vector methods in 3D: vectors perpendicular to a plane, the perpendicular distance between two parallel planes",
    ],
    skills: ["vectors", "geometry"],
    prerequisites: ["em-3"],
    weight: 1.1,
    paper: "em-p2",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },

  // ------------------------------------------------------- STATISTICS (P3 A)
  {
    id: "em-s1",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 1",
    title: "Statistical sampling",
    group: STATS,
    content: [
      "Population, sample, sample frame, sample size, sampling fraction, census and sample",
      "Simple random, systematic, stratified and quota sampling; opportunities for bias",
      "Reliability of data; sampling methods and their advantages and disadvantages in context",
    ],
    skills: ["statistics", "sampling"],
    prerequisites: [],
    weight: 0.8,
    paper: "em-p3",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-s2",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 2",
    title: "Descriptive statistics",
    group: STATS,
    content: [
      "Data presentation and interpretation: tables, stem-and-leaf diagrams, box plots, cumulative frequency graphs, histograms (including unequal class intervals)",
      "Measures of central tendency: mean, median and mode, and their advantages and disadvantages",
      "Measures of spread: range, interquartile range, variance, standard deviation and their interpretation",
      "Measures of skewness and the effect of outliers; identify and justify the most appropriate summary statistics for a given large data set",
      "Use of large data sets, and conditional probability from grouped data",
    ],
    skills: ["statistics", "graphs"],
    prerequisites: ["em-s1"],
    weight: 1,
    paper: "em-p3",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-s3",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 3",
    title: "Probability",
    group: STATS,
    content: [
      "The probability axioms; mutually exclusive, independent and conditional events",
      "Probability calculations using Venn diagrams, tree diagrams, permutations and combinations",
      "Conditional probability using P(A|B) = P(A \u2229 B)/P(B), and Bayes' theorem",
      "Reliability and validity of data; critique of sampling methods",
    ],
    skills: ["probability", "statistics"],
    prerequisites: ["em-s1"],
    weight: 1.1,
    paper: "em-p3",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-s4",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 4",
    title: "Random variables and distributions",
    group: STATS,
    content: [
      "Concept of a random variable, and the probability distribution of a discrete random variable",
      "Use of the mathematical expectation E(X) and of the standard deviation of a discrete random variable",
      "Binomial distribution: conditions for applicability, calculation of probabilities and of the expectation",
      "Cumulative probabilities and inverse problems for the binomial distribution",
    ],
    skills: ["probability", "statistics"],
    prerequisites: ["em-s3"],
    weight: 1.1,
    paper: "em-p3",
    asLevel: true,
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-s5",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 5",
    title: "Statistical distributions",
    group: STATS,
    content: [
      "The normal distribution and the use of the \u03c6 and \u03c8 percentages point table",
      "Standard deviation and the symmetry of the normal distribution; express in terms of mean and standard deviation",
      "Probability calculations with the normal distribution, including inverse problems and the effect of a change of mean or standard deviation",
      "Use of the normal approximation to the binomial distribution, including continuity corrections",
    ],
    skills: ["statistics", "probability"],
    prerequisites: ["em-s4"],
    weight: 1.2,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-s6",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 6",
    title: "Statistical hypothesis testing",
    group: STATS,
    content: [
      "The null and alternative hypotheses; one-tailed and two-tailed tests",
      "Use of the p-value, significance level and critical values to accept or reject a hypothesis",
      "Type I and Type II errors, and the relationship between significance level and the probability of a Type I error",
      "Reasons a Type I error is more serious for some investigations than others",
    ],
    skills: ["statistics", "hypothesis-testing"],
    prerequisites: ["em-s5"],
    weight: 1,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-s7",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 7",
    title: "Further probability",
    group: STATS,
    content: [
      "Modelling assumptions and their effect on probabilities; critique of given models",
      "Probability generating functions and the use of generating functions to determine distributions",
      "Expectation and variance in the form E(X\u00b2) \u2212 (E(X))\u00b2",
    ],
    skills: ["probability", "statistics"],
    prerequisites: ["em-s4"],
    weight: 1,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-s8",
    subject: "edexcel-mathematics",
    specRef: "Statistics Topic 8",
    title: "Further statistics",
    group: STATS,
    content: [
      "Least squares regression and the line of best fit; use of residuals to assess the model",
      "Interpretation of the correlation coefficient and the coefficient of determination; using a change of variables",
      "The meaning of the correlation coefficient, and the effect of an outlier or a small sample on it",
    ],
    skills: ["statistics", "graphs"],
    prerequisites: ["em-s2"],
    weight: 1,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },

  // -------------------------------------------------------- MECHANICS (P3 B)
  {
    id: "em-m1",
    subject: "edexcel-mathematics",
    specRef: "Mechanics Topic 1",
    title: "Kinematics",
    group: MECH,
    content: [
      "Quantities and units in mechanics; units and dimensions, including conversion",
      "Kinematic quantities: displacement, speed, velocity and acceleration; average and instantaneous definitions",
      "Motion in a straight line, including direction of motion and distance-time and velocity-time graphs",
      "Constant acceleration formulae (SUVAT): v = u + at, s = \u00bd(u + v)t, s = ut + \u00bdat\u00b2, v\u00b2 = u\u00b2 + 2as",
      "Motion in two dimensions: resolving motion into components and the Pythagoras relation for resultant velocity",
      "Vector methods in kinematics, including position vectors, i and j notation, and acceleration in a fixed direction",
      "Motion in a variable direction; relative velocity and the concept of a frame of reference",
    ],
    skills: ["mechanics", "kinematics", "vectors"],
    prerequisites: ["em-10"],
    weight: 1.2,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-m2",
    subject: "edexcel-mathematics",
    specRef: "Mechanics Topic 2",
    title: "Forces and Newton's laws",
    group: MECH,
    content: [
      "Modelling in mechanics; stating modelling assumptions and using diagrams to represent physical situations",
      "Force diagrams and resultant force; weight, normal reaction, friction, drag, thrust and tension",
      "Equilibrium and Newton's three laws; resultant force and acceleration for a particle, F = ma",
      "Motion in two dimensions using components, including projectile motion with gravity as a constant acceleration",
      "Free-body diagrams, resolving forces and applying Newton's second law in component form",
    ],
    skills: ["mechanics", "vectors"],
    prerequisites: ["em-m1"],
    weight: 1.2,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-m3",
    subject: "edexcel-mathematics",
    specRef: "Mechanics Topic 3",
    title: "Moments and couples",
    group: MECH,
    content: [
      "Moments about a point and about a line, including the moment of a force about a point",
      "Couples; resultant moment of a system of coplanar forces, and the principle of moments",
      "Equilibrium of a rigid body under coplanar forces; centre of mass and its calculation for a lamina or a wire frame",
      "Solve problems in equilibrium including hanging and suspended objects, ladders and frames",
    ],
    skills: ["mechanics", "geometry"],
    prerequisites: ["em-m2"],
    weight: 1.1,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-m4",
    subject: "edexcel-mathematics",
    specRef: "Mechanics Topic 4",
    title: "Work, energy and power",
    group: MECH,
    content: [
      "Energy: kinetic and gravitational potential energy, and conservation of energy",
      "Work done by a force, including work done against friction and resultant work done",
      "Work\u2013energy principle for a particle; escape velocity and terminal velocity",
      "Power as the rate of doing work; efficiency as a ratio of output to input power",
      "Solve problems involving kinetic energy in collisions and the energy lost in collisions",
    ],
    skills: ["mechanics", "calculus"],
    prerequisites: ["em-m2"],
    weight: 1.2,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-m5",
    subject: "edexcel-mathematics",
    specRef: "Mechanics Topic 5",
    title: "Momentum",
    group: MECH,
    content: [
      "Conservation of linear momentum in a closed system, solved using component form",
      "Impulse as the product of force and time for a force\u2013time graph, and impulse\u2013momentum equation",
      "Elastic and inelastic collisions; coefficient of restitution and Newton's law of restitution",
      "Solve problems on collisions including two-dimensional impacts and explosions",
    ],
    skills: ["mechanics", "vectors"],
    prerequisites: ["em-m2"],
    weight: 1.1,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
  {
    id: "em-m6",
    subject: "edexcel-mathematics",
    specRef: "Mechanics Topic 6",
    title: "Further dynamics",
    group: MECH,
    content: [
      "Simple harmonic motion; period, amplitude and the relationship between angular frequency and period",
      "Use of the SHM formulae for displacement, velocity and acceleration at any point in the cycle",
      "Energy in SHM and damping; explain damping in terms of energy transferred to the surroundings",
      "Circular motion; centripetal acceleration and the forces providing it",
      "Motion in a vertical circle; non-uniform circular motion and the condition for loss of contact",
    ],
    skills: ["mechanics", "calculus", "trigonometry"],
    prerequisites: ["em-m5"],
    weight: 1.1,
    paper: "em-p3",
    examBoard: "Pearson Edexcel A level Mathematics (9MA0)",
  },
];
