import type { Chapter, Paper } from "@/lib/types";

export const OCR_PAPERS: Paper[] = [
  {
    id: "ocr-01",
    subject: "ocr-computer-science",
    code: "H446/01",
    title: "Computer systems",
    durationMinutes: 150,
    marks: 140,
    weighting: 40,
  },
  {
    id: "ocr-02",
    subject: "ocr-computer-science",
    code: "H446/02",
    title: "Algorithms and programming",
    durationMinutes: 150,
    marks: 140,
    weighting: 40,
  },
  {
    id: "ocr-03",
    subject: "ocr-computer-science",
    code: "H446/03",
    title: "Programming project",
    durationMinutes: 0,
    marks: 70,
    weighting: 20,
  },
];

const C1 = "Component 01: Computer systems";
const C2 = "Component 02: Algorithms and programming";
const BOARD = "Cambridge OCR AS and A level Computer Science (H046/H446)";

export const OCR_CS_COMPONENT1: Chapter[] = [
  {
    id: "ocr-1.1.1",
    subject: "ocr-computer-science",
    specRef: "1.1.1",
    title: "Structure and function of the processor",
    group: C1,
    content: [
      "The Arithmetic and Logic Unit; ALU, Control Unit and Registers",
      "Registers: Program Counter (PC), Accumulator (ACC), Memory Address Register (MAR), Memory Data Register (MDR), Current Instruction Register (CIR)",
      "Buses: data, address and control; how this relates to assembly language programs",
      "The fetch-execute cycle, including the role each register plays in it",
      "How the address bus and data bus carry instructions and operands between components",
    ],
    skills: ["computer-architecture", "fetch-execute"],
    prerequisites: [],
    weight: 1.2,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.1.2",
    subject: "ocr-computer-science",
    specRef: "1.1.2",
    title: "Types of processor",
    group: C1,
    content: [
      "The differences between and uses of CISC and RISC processors",
      "GPUs and their uses, including those not related to graphics",
      "Multicore and parallel systems",
      "The performance of a processor: clock speed, cores, cache size, architecture and instruction set length",
      "Amdahl's law and the limits of parallel speed-up",
    ],
    skills: ["computer-architecture", "performance"],
    prerequisites: ["ocr-1.1.1"],
    weight: 1,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.1.3",
    subject: "ocr-computer-science",
    specRef: "1.1.3",
    title: "Input, output and storage",
    group: C1,
    content: [
      "How different input, output and storage devices can be applied to the solution of different problems",
      "The uses of magnetic, flash and optical storage devices",
      "RAM and ROM, including the terms non-volatile, read-only, read/write and addressable",
      "Virtual storage and paging",
      "Measures of storage capacity, access time and throughput when comparing devices",
    ],
    skills: ["hardware", "storage"],
    prerequisites: ["ocr-1.1.1"],
    weight: 1.1,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.2.1",
    subject: "ocr-computer-science",
    specRef: "1.2.1",
    title: "Systems software",
    group: C1,
    content: [
      "Operating system components, including the kernel, device drivers, file system and user interface",
      "Memory management: contiguous, paging, segmentation, virtual memory and the use of paging",
      "Process management and the use of a scheduler; the terms preemptive, priority and throughput",
      "Interrupts and the use of polling as an alternative",
      "Deadlock and the conditions for a deadlock to occur",
    ],
    skills: ["operating-systems", "memory-management"],
    prerequisites: ["ocr-1.1.1"],
    weight: 1.3,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.2.2",
    subject: "ocr-computer-science",
    specRef: "1.2.2",
    title: "Applications generation",
    group: C1,
    content: [
      "Stages of the generation of an application, including the design, build and test stages",
      "Translation: lexical analysis, syntax analysis, code generation and optimisation",
      "Linkers and loaders and use of libraries",
      "The difference between compilers and interpreters",
      "Software testing techniques, including unit testing, integration testing and user acceptance testing",
    ],
    skills: ["compilers", "testing", "software-development"],
    prerequisites: ["ocr-1.2.1"],
    weight: 1,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.2.3",
    subject: "ocr-computer-science",
    specRef: "1.2.3",
    title: "Software development",
    group: C1,
    content: [
      "Waterfall lifecycle: analysis, design, implementation, testing, maintenance and deployment",
      "Agile methodologies, specifically extreme programming; the spiral model and rapid application development",
      "User and system requirements, and the difference between them",
      "Documentation and the use of CASE tools and diagrams during system development",
      "Maintenance, including the categories of preventive, corrective and adaptive maintenance",
    ],
    skills: ["software-development", "waterfall", "agile"],
    prerequisites: ["ocr-1.2.2"],
    weight: 1,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.2.4",
    subject: "ocr-computer-science",
    specRef: "1.2.4",
    title: "Types of programming language",
    group: C1,
    content: [
      "Use of assembly language, addressing modes and their relationship to machine code",
      "Assembly: instructions using operation codes, addressing operands, and comments in assembly code",
      "Classification of programming languages: machine code, assembly, high-level languages, scripting languages",
      "Advantages and disadvantages of machine code and assembly compared with high-level languages",
      "Paradigms including procedural, object-oriented and declarative languages",
    ],
    skills: ["assembly", "programming-languages"],
    prerequisites: ["ocr-1.1.1"],
    weight: 1.1,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.3.1",
    subject: "ocr-computer-science",
    specRef: "1.3.1",
    title: "Compression, encryption and hashing",
    group: C1,
    content: [
      "Lossy and lossless compression and the difference between them",
      "RLE and run-length encoding; the impact of compression on file size and loss of data",
      "Auditory and image compression: sampling resolution and colour depth",
      "Encryption: symmetric (private key) and asymmetric (public key) encryption",
      "Hashing and the use of hash tables to store and retrieve data",
    ],
    skills: ["compression", "encryption", "hashing"],
    prerequisites: [],
    weight: 1.2,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.3.2",
    subject: "ocr-computer-science",
    specRef: "1.3.2",
    title: "Databases",
    group: C1,
    content: [
      "Relational databases: tables made up of attributes and records, with primary and secondary keys",
      "Redundancy, relation modelling and normalisation to 1NF, 2NF and 3NF",
      "Relational algebra, including selection, projection and join operations",
      "SQL queries to create, populate and extract data, including SELECT, INSERT, UPDATE and DELETE",
      "Using interface tools to insert, edit and delete data and to extract data from a database",
    ],
    skills: ["databases", "sql", "normalisation"],
    prerequisites: [],
    weight: 1.3,
    paper: "ocr-01",
    examBoard: BOARD,
  },
  {
    id: "ocr-1.3.3",
    subject: "ocr-computer-science",
    specRef: "1.3.3",
    title: "Networks",
    group: C1,
    content: [
      "Types of network: LAN, WAN, client-server and peer-to-peer, and their characteristics and appropriate uses",
      "The internet structure: the TCP/IP stack, DNS, protocol layering, LANs and WANs",
      "Packet and circuit switching, including the use of packet headers and MTU",
      "Protocols: TCP, UDP, HTTP, HTTPS, FTP, SMTP, POP3 and IMAP",
      "Network hardware: routers, switches, bridges, modems and network interface cards",
    ],
    skills: ["networks", "protocols"],
    prerequisites: [],
    weight: 1.3,
    paper: "ocr-01",
    examBoard: BOARD,
  },
  {
    id: "ocr-1.3.4",
    subject: "ocr-computer-science",
    specRef: "1.3.4",
    title: "Web technologies",
    group: C1,
    content: [
      "Web design: HTML, CSS and the box model",
      "HTTP request and response structure, including status codes",
      "Cookies and sessions for maintaining state between requests",
      "Web databases and web server-side scripting",
      "Client-side and server-side processing; the difference between them and their security implications",
    ],
    skills: ["web", "http"],
    prerequisites: ["ocr-1.3.3"],
    weight: 0.9,
    paper: "ocr-01",
    examBoard: BOARD,
  },
  {
    id: "ocr-1.4.1",
    subject: "ocr-computer-science",
    specRef: "1.4.1",
    title: "Data types",
    group: C1,
    content: [
      "Data types: integer, real, boolean, character, string and date; including integer ranges and overflow",
      "Unsigned and signed binary representation; two's complement",
      "Hexadecimal and denary and their conversion, including use of the nibble",
      "Character sets (ASCII and UNICODE) and how they are used to represent text",
      "Bitwise operations: AND, OR, XOR, NOT and logical left and right shifts, including twos-complement",
      "Real numbers and denormalised and normalised floating point representation",
    ],
    skills: ["binary", "hex", "bitwise", "data-representation"],
    prerequisites: [],
    weight: 1.5,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.4.2",
    subject: "ocr-computer-science",
    specRef: "1.4.2",
    title: "Data structures",
    group: C1,
    content: [
      "Arrays of up to three dimensions, records, lists, tuples and dictionaries",
      "Relational databases as a data structure; use of indices and keys",
      "Abstract data types (ADTs): stack, queue and linked list, and their key features",
      "Justify the use of a given data structure for a given situation",
      "Trees and graphs as data structures: binary search trees, linked lists and graphs",
      "Create, traverse, add data to and remove data from stacks, queues and linked lists",
    ],
    skills: ["data-structures", "stacks-queues", "trees-graphs"],
    prerequisites: [],
    weight: 1.4,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.4.3",
    subject: "ocr-computer-science",
    specRef: "1.4.3",
    title: "Boolean algebra",
    group: C1,
    content: [
      "Logic values and logic operators: NOT, AND, OR",
      "Deriving one statement from another using rules of Boolean algebra, including De Morgan's Laws, distribution, association, commutation and double negation",
      "Canonical form and the simplification of a Boolean expression",
      "Using Boolean algebra to describe and simplify combinations of logic gates",
      "Half adders, full adders and truth tables",
    ],
    skills: ["boolean-algebra", "logic"],
    prerequisites: [],
    weight: 1.2,
    paper: "ocr-01",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-1.5.1",
    subject: "ocr-computer-science",
    specRef: "1.5.1",
    title: "Computing legislation",
    group: C1,
    content: [
      "Data Protection Act (2018) and UK GDPR: data controller, data subject, lawfulness of processing",
      "Computer Misuse Act 1990: unauthorised access and computer-related offences",
      "Copyright, Designs and Patents Act 1988; software and data protection implications",
      "Intellectual property rights: patents, trademarks and licences",
      "Data subject rights: subject access, right to erasure and data portability",
    ],
    skills: ["legislation", "ethics"],
    prerequisites: [],
    weight: 0.9,
    paper: "ocr-01",
    examBoard: BOARD,
  },
  {
    id: "ocr-1.5.2",
    subject: "ocr-computer-science",
    specRef: "1.5.2",
    title: "Moral and ethical issues",
    group: C1,
    content: [
      "What is meant by technology ethics and the ethical issues arising from the use of IT",
      "Current legislation and its impact on society; balancing individual rights with the public interest",
      "Different views on the impact of computing technology: technocentric and anthropocentric",
      "Environmental impact of computing and e-waste; sustainability",
      "Social and cultural issues: surveillance, digital divide, automation and AI bias",
    ],
    skills: ["ethics", "society"],
    prerequisites: [],
    weight: 0.9,
    paper: "ocr-01",
    examBoard: BOARD,
  },
];

export const OCR_CS_COMPONENT2: Chapter[] = [
  {
    id: "ocr-2.1.1",
    subject: "ocr-computer-science",
    specRef: "2.1.1",
    title: "Thinking abstractly",
    group: C2,
    content: [
      "The process of abstraction; solving problems by identifying the essential aspects of a problem",
      "Decomposition: breaking a problem down into smaller, more manageable sub-problems",
      "Recognising patterns, similarities and differences in problem situations",
      "Abstraction, decomposition and generalisation as aspects of computational thinking",
    ],
    skills: ["computational-thinking", "abstraction"],
    prerequisites: [],
    weight: 1,
    paper: "ocr-02",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-2.1.2",
    subject: "ocr-computer-science",
    specRef: "2.1.2",
    title: "Thinking ahead",
    group: C2,
    content: [
      "The meaning of 'thinking ahead' and prediction of what will happen and when",
      "Preconditions and postconditions used to describe an algorithm",
      "Trace tables and dry runs; hand and dry execution of algorithms",
      "Recognition of the need to test boundary cases, including zero, one and negative inputs",
    ],
    skills: ["computational-thinking", "trace-tables"],
    prerequisites: ["ocr-2.1.1"],
    weight: 1.1,
    paper: "ocr-02",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-2.1.3",
    subject: "ocr-computer-science",
    specRef: "2.1.3",
    title: "Thinking procedurally",
    group: C2,
    content: [
      "The meaning of 'thinking procedurally' and the order of instructions in a solution",
      "Constructing an algorithm from a written specification",
      "Turning a procedural solution into working code",
      "Identifying the inputs, processes and outputs of a program",
    ],
    skills: ["computational-thinking", "algorithms"],
    prerequisites: ["ocr-2.1.1"],
    weight: 1.1,
    paper: "ocr-02",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-2.1.4",
    subject: "ocr-computer-science",
    specRef: "2.1.4",
    title: "Thinking logically",
    group: C2,
    content: [
      "The meaning of 'thinking logically' and using logic to describe a situation",
      "Boolean logic; conditions and the use of AND, OR and NOT in combining conditions",
      "Deductive reasoning and using logic to find and correct errors in a solution",
      "Truth tables and deriving an algorithm's behaviour from its logic",
    ],
    skills: ["computational-thinking", "boolean-algebra"],
    prerequisites: ["ocr-1.4.3"],
    weight: 1.2,
    paper: "ocr-02",
    examBoard: BOARD,
  },
  {
    id: "ocr-2.1.5",
    subject: "ocr-computer-science",
    specRef: "2.1.5",
    title: "Thinking concurrently",
    group: C2,
    content: [
      "The meaning of 'thinking concurrently' and identifying concurrent tasks",
      "When concurrency improves a solution and when it does not",
      "Consideration of shared resources and race conditions",
      "Multicore systems, parallel processing and pipelining",
    ],
    skills: ["computational-thinking", "concurrency"],
    prerequisites: ["ocr-1.1.2"],
    weight: 0.9,
    paper: "ocr-02",
    examBoard: BOARD,
  },
  {
    id: "ocr-2.2.1",
    subject: "ocr-computer-science",
    specRef: "2.2.1",
    title: "Programming techniques",
    group: C2,
    content: [
      "Programming constructs: sequence, iteration and branching",
      "Recursion, how it can be used and compared to an iterative approach",
      "Global and local variables; scope of variables",
      "Modularity, functions and procedures, parameter passing by value and by reference",
      "Use of an IDE to develop and debug a program",
      "Use of object-oriented techniques: classes, objects, encapsulation, inheritance and polymorphism",
      "Exception handling and when it is appropriate to use it",
    ],
    skills: ["programming", "recursion", "oop"],
    prerequisites: ["ocr-2.1.3"],
    weight: 1.5,
    paper: "ocr-02",
    asLevel: true,
    examBoard: BOARD,
  },
  {
    id: "ocr-2.2.2",
    subject: "ocr-computer-science",
    specRef: "2.2.2",
    title: "Computational methods",
    group: C2,
    content: [
      "Features that make a problem solvable by computational methods",
      "Problem recognition, problem decomposition and divide and conquer",
      "Use of abstraction and the role of modelling",
      "Apply knowledge of backtracking, data mining, heuristics, performance modelling, pipelining and visualisation",
    ],
    skills: ["computational-methods", "heuristics"],
    prerequisites: ["ocr-2.1.5"],
    weight: 1,
    paper: "ocr-02",
    examBoard: BOARD,
  },
  {
    id: "ocr-2.3.1",
    subject: "ocr-computer-science",
    specRef: "2.3.1",
    title: "Algorithms",
    group: C2,
    content: [
      "Standard algorithms: bubble sort, insertion sort, merge sort and quicksort",
      "Standard searching algorithms: linear search and binary search",
      "Algorithms for stacks and queues; push, pop, enqueue and dequeue",
      "Trace tables and dry runs; hand and dry execution of algorithms",
      "Binary trees and algorithms for traversing binary trees: pre-order, in-order and post-order",
      "Graphs, tree-based and other algorithms; Dijkstra's and A* algorithms on weighted graphs",
      "Searching and sorting algorithms; finding the minimum or maximum value",
      "The halving algorithm for finding the median and the binary search algorithm",
    ],
    skills: ["algorithms", "sorting", "searching", "trees-graphs"],
    prerequisites: ["ocr-1.4.2", "ocr-2.1.2"],
    weight: 1.7,
    paper: "ocr-02",
    asLevel: true,
    examBoard: BOARD,
  },
];

export const OCR_CS_CHAPTERS: Chapter[] = [...OCR_CS_COMPONENT1, ...OCR_CS_COMPONENT2];
