import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { type MarkCorpus, validateCorpus } from "../src/lib/mark-corpus";
import { evaluateCorpus } from "../src/lib/mark-model";

/*
  Train the marking model and report what it is actually worth.

  The output that matters is the precision table, not the training accuracy. A
  model fitted on a few hundred examples will report a near-perfect score on the
  data it was trained on, which says nothing except that it memorised; the
  cross-validated figures are the only ones reported as a reason to trust it.

  Anything that does not clear the precision bar is written to the trust file as
  untrusted, and the app then leaves those points with the learner. An empty
  trusted list is a normal outcome, not a failure of the script.

  Usage: npx tsx scripts/train-mark-model.ts
*/

const ROOT = resolve(import.meta.dirname, "..");
const CORPUS = join(ROOT, ".cache", "corpus", "corpus.json");
const TRUST = join(ROOT, "src", "lib", "generated", "mark-trust.json");

function pct(n: number): string {
  return `${(n * 100).toFixed(1)}%`;
}

function main(): void {
  if (!existsSync(CORPUS)) {
    console.error(`No corpus at ${CORPUS}.`);
    console.error("Run scripts/fetch-mark-corpus.ts first. See corpus/README.md for what may be used.");
    process.exitCode = 1;
    return;
  }

  const { corpus, problems, rejected } = validateCorpus(
    JSON.parse(readFileSync(CORPUS, "utf8")) as unknown,
  ) as { corpus: MarkCorpus; problems: unknown[]; rejected: unknown[] };

  if (problems.length > 0) {
    console.error("The corpus did not validate, so nothing was trained:");
    for (const p of problems.slice(0, 10)) console.error(`  ${JSON.stringify(p)}`);
    process.exitCode = 1;
    return;
  }

  console.log(`corpus: ${corpus.items.length} items, ${rejected.length} rejected rows`);
  console.log(
    `sources: ${corpus.provenance.map((p) => `${p.source} (${p.licence})`).join(", ") || "none"}\n`,
  );

  const report = evaluateCorpus(corpus);

  const pad = (s: string, n: number) => s.padEnd(n).slice(0, n);
  console.log(`${pad("point type", 42)} ${pad("n", 6)} ${pad("prec", 8)} ${pad("recall", 8)} ${pad("F1", 8)} verdict`);
  for (const row of report.byLabel) {
    console.log(
      `${pad(row.label, 42)} ${pad(String(row.cv.support), 6)} ${pad(pct(row.cv.precision), 8)} ${pad(
        pct(row.cv.recall),
        8,
      )} ${pad(pct(row.cv.f1), 8)} ${row.trusted ? "AUTO" : "learner"}`,
    );
  }

  if (report.limitation) console.log(`\n${report.limitation}`);
  console.log(
    `\n${report.trusted.length} of ${report.byLabel.length} point types cleared the precision bar.`,
  );

  mkdirSync(join(ROOT, "src", "lib", "generated"), { recursive: true });
  writeFileSync(
    TRUST,
    `${JSON.stringify(
      {
        note: "Generated by scripts/train-mark-model.ts. Do not edit by hand.",
        trustedLabels: report.trusted,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
  console.log(`wrote ${TRUST}`);
}

main();